apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kubes-tech-tls
spec:
  secretName: kubes-tech
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kubes.tech
  dnsNames:
    - kubes.tech
    - www.kubes.tech
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kubes.tech
          - www.kubes.tech
      
